[build]
  command = "npm run build"
  publish = "dist"

# 1. IL NOSTRO PONTE PRIVATO (PROXY NETLIFY)
[[redirects]]
  from = "/api-unisalento/*"
  to = "https://logistica.unisalento.it/:splat"
  status = 200
  force = true

# 2. Fix per tenere l'app aperta ricaricando la pagina
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200