/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

self.skipWaiting();
clientsClaim();

/**
 * Ascolta l'evento 'push' dal server di notifiche.
 * Il payload deve contenere i dati della notifica in formato JSON.
 */
self.addEventListener('push', (event) => {
  if (!event.data) {
    console.warn('Push event received without data');
    return;
  }

  try {
    const data = event.data.json();
    const { title, body, icon, tag, data: extraData } = data;

    const options: NotificationOptions = {
      body: body || 'Hai una nuova lezione in arrivo!',
      icon: icon || '/logo192.png',
      badge: '/favicon.ico', // Icona piccola mostrata nella barra di stato su Android
      tag: tag || 'lesson-notification', // Evita notifiche duplicate per lo stesso tag
      renotify: true, // Vibra anche se il tag è uguale
      vibrate: [200, 100, 200], // Pattern di vibrazione [ms on, ms off, ms on]
      data: extraData || {}, // Dati extra passabili alla notifica
      actions: [
        {
          action: 'open',
          title: 'Apri App'
        }
      ]
    };

    event.waitUntil(
      self.registration.showNotification(title || 'NextLesson UniSalento', options)
    );
  } catch (error) {
    console.error('Error parsing push data:', error);
    
    // Fallback in caso di payload non JSON
    event.waitUntil(
      self.registration.showNotification('NextLesson UniSalento', {
        body: event.data.text(),
        icon: '/logo192.png'
      })
    );
  }
});

/**
 * Gestisce l'interazione dell'utente con la notifica (click).
 */
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // URL da aprire al click della notifica
  const urlToOpen = new URL('/', self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Se c'è già una tab aperta, mettila a fuoco
      for (const client of windowClients) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // Altrimenti apri una nuova tab
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
